updated .yml conditional check.migrations

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,7 +45,7 @@ jobs:
           pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Apply Migrations
+            - name: Apply Migrations
         working-directory: ecommerce-backend
         env:
           FLASK_APP: app
@@ -60,8 +60,11 @@ jobs:
           PYTHONPATH: ${{ github.workspace }}/ecommerce-backend
         run: |
           source venv/bin/activate
-          if [ ! -d "migrations/versions" ]; then flask db init; fi
-          flask db migrate -m "Auto migration"
+          if [ ! -d "migrations" ]; then
+            echo "⚠️ Migrations folder missing. Initializing database..."
+            flask db init
+          fi
+          flask db migrate -m "Auto migration" || echo "⚠️ No new migrations detected."
           flask db upgrade
           python tests/db_seed.py
 
